const STORAGE_KEY="better_you_21_days_v1";
const ASPECTS={spirit:{title:"الجانب الروحي",className:"spirit",tasks:["الصلاة في وقتها","ورد قرآن يومي","100 استغفار","دعاء أو قيام ولو قليلًا","عمل خفي لا يعلم به أحد"]},sport:{title:"الجانب الرياضي",className:"sport",tasks:["رياضة أو مشي 20 دقيقة","شرب كمية ماء مناسبة","تقليل السكريات أو المشروبات الغازية","تمرين إطالة أو تنفس","نوم أكثر انضباطًا"]},mind:{title:"الجانب الفكري والثقافي",className:"mind",tasks:["قراءة 10 صفحات أو 15 دقيقة","تعلم فكرة جديدة","كتابة ملخص أو فائدة","مشاهدة محتوى تعليمي نافع","حفظ مفهوم أو عبارة مفيدة"]},social:{title:"الجانب الاجتماعي",className:"social",tasks:["بر الوالدين أو مساعدة الأسرة","رسالة طيبة لشخص","ترك الغيبة أو السخرية","الإصغاء الجيد لشخص","مساعدة أو خدمة بلا مقابل"]}};
const aspectKeys=Object.keys(ASPECTS);
function createInitialState(){return{name:"",activeDay:1,finalComment:"",days:Array.from({length:21},(_,i)=>({day:i+1,reflection:"",feeling:"",aspects:aspectKeys.reduce((acc,key)=>{acc[key]=Array(ASPECTS[key].tasks.length).fill(false);return acc;},{})}))}}
let state=createInitialState();
const el=id=>document.getElementById(id);
function load(){const saved=localStorage.getItem(STORAGE_KEY);if(saved){try{state=JSON.parse(saved)}catch(error){localStorage.removeItem(STORAGE_KEY);state=createInitialState()}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function getDayTotal(dayObj){return aspectKeys.reduce((sum,key)=>sum+dayObj.aspects[key].filter(Boolean).length,0)}
function totalTaskCountPerDay(){return aspectKeys.reduce((sum,key)=>sum+ASPECTS[key].tasks.length,0)}
function totals(){const allTasksPerAspect=21*5;const aspectCompleted={};let completedTasks=0;aspectKeys.forEach(key=>{const count=state.days.reduce((sum,day)=>sum+day.aspects[key].filter(Boolean).length,0);aspectCompleted[key]=count;completedTasks+=count});const totalTasks=totalTaskCountPerDay()*21;const completedDays=state.days.filter(day=>getDayTotal(day)>0).length;const aspectPercents=aspectKeys.reduce((acc,key)=>{acc[key]=Math.round(aspectCompleted[key]/allTasksPerAspect*100);return acc},{});const overallPercent=Math.round(completedTasks/totalTasks*100);return{completedTasks,completedDays,totalTasks,overallPercent,aspectPercents}}
function scoreLabel(percent){if(percent>=90)return"امتياز";if(percent>=75)return"ممتاز";if(percent>=60)return"جيد جدًا";if(percent>=45)return"جيد";return"تحتاج إلى استمرار أقوى"}
function encouragement(percent){if(percent>=90)return"أحسنت. لقد أظهرت التزامًا عاليًا ونموًا متوازنًا في رحلتك. استمر، ولا تجعل نهاية البرنامج نهاية الطريق.";if(percent>=75)return"نتيجتك قوية ومبشرة. أصبحت لديك أرضية جميلة في أكثر من جانب، والأهم الآن أن تحافظ على الاستمرار.";if(percent>=60)return"قطعت شوطًا جيدًا. لديك تقدم واضح، وما تحتاجه الآن هو تثبيت العادات التي نجحت معك وتطوير الجوانب الأضعف.";return"بدايتك مهمة حتى لو لم تكتمل. القيمة ليست في الكمال، بل في العودة والاستمرار والمحاولة من جديد."}
function renderAspectSummaryCards(t){const container=el("aspectSummaryCards");container.innerHTML="";aspectKeys.forEach(key=>{const card=document.createElement("div");card.className=`aspect-summary-card ${ASPECTS[key].className}`;card.innerHTML=`<span>${ASPECTS[key].title}</span><strong>${t.aspectPercents[key]}%</strong>`;container.appendChild(card)})}
function renderDays(){const grid=el("daysGrid");grid.innerHTML="";state.days.forEach(day=>{const btn=document.createElement("button");btn.className="day-btn"+(day.day===state.activeDay?" active":"")+(getDayTotal(day)>0?" done":"");btn.textContent=day.day;btn.onclick=()=>{state.activeDay=day.day;save();render()};grid.appendChild(btn)})}
function renderAspectCards(currentDay){const container=el("aspectsContainer");container.innerHTML="";aspectKeys.forEach(key=>{const aspect=ASPECTS[key];const aspectDone=currentDay.aspects[key].filter(Boolean).length;const card=document.createElement("div");card.className=`aspect-card ${aspect.className}`;card.innerHTML=`<div class="aspect-head"><h3>${aspect.title}</h3><span class="aspect-badge ${aspect.className}">${aspectDone}/5</span></div><div class="task-list" id="task-list-${key}"></div>`;container.appendChild(card);const taskList=card.querySelector(`#task-list-${key}`);aspect.tasks.forEach((task,index)=>{const taskBtn=document.createElement("button");taskBtn.className="task-btn"+(currentDay.aspects[key][index]?" done":"");taskBtn.innerHTML=`<span class="task-check">${currentDay.aspects[key][index]?"✓":"○"}</span><span>${task}</span>`;taskBtn.onclick=()=>{currentDay.aspects[key][index]=!currentDay.aspects[key][index];save();render()};taskList.appendChild(taskBtn)})})}
function updateCertificate(t){el("certName").textContent=state.name.trim()||"اسم المشارك";el("certOverallPercent").textContent=`${t.overallPercent}%`;el("certScore").textContent=scoreLabel(t.overallPercent);el("certDate").textContent=new Date().toLocaleDateString("ar-SA");el("certSpiritPercent").textContent=`${t.aspectPercents.spirit}%`;el("certSportPercent").textContent=`${t.aspectPercents.sport}%`;el("certMindPercent").textContent=`${t.aspectPercents.mind}%`;el("certSocialPercent").textContent=`${t.aspectPercents.social}%`;el("certMessage").textContent=encouragement(t.overallPercent);if(state.finalComment.trim()){const safe=state.finalComment.replaceAll("<","&lt;").replaceAll(">","&gt;");el("certComment").innerHTML=`<strong>تعليق المشارك:</strong><br>${safe}`;el("certComment").style.display="block"}else{el("certComment").style.display="none";el("certComment").innerHTML=""}}
function render(){const currentDay=state.days[state.activeDay-1];const t=totals();el("participantName").value=state.name;el("overallPercentText").textContent=`${t.overallPercent}%`;el("overallProgressBar").style.width=`${t.overallPercent}%`;el("completedDays").textContent=t.completedDays;el("completedTasks").textContent=t.completedTasks;el("dayBadge").textContent=`اليوم ${state.activeDay}`;el("todayScore").textContent=`${getDayTotal(currentDay)}/${totalTaskCountPerDay()}`;el("reflection").value=currentDay.reflection;el("feeling").value=currentDay.feeling;el("finalComment").value=state.finalComment;el("scoreLabel").textContent=scoreLabel(t.overallPercent);el("encouragement").textContent=encouragement(t.overallPercent);el("prevDay").disabled=state.activeDay===1;el("nextDay").disabled=state.activeDay===21;const certReady=t.completedDays===21&&state.name.trim().length>1;el("printCert").disabled=!certReady;el("certHint").style.display=certReady?"none":"block";renderAspectSummaryCards(t);renderDays();renderAspectCards(currentDay);updateCertificate(t)}
document.addEventListener("DOMContentLoaded",()=>{load();el("participantName").oninput=e=>{state.name=e.target.value;save();render()};el("reflection").oninput=e=>{state.days[state.activeDay-1].reflection=e.target.value;save()};el("feeling").oninput=e=>{state.days[state.activeDay-1].feeling=e.target.value;save()};el("finalComment").oninput=e=>{state.finalComment=e.target.value;save();updateCertificate(totals())};el("prevDay").onclick=()=>{state.activeDay=Math.max(1,state.activeDay-1);save();render()};el("nextDay").onclick=()=>{state.activeDay=Math.min(21,state.activeDay+1);save();render()};el("resetBtn").onclick=()=>{const ok=confirm("هل تريد إعادة البرنامج من البداية؟ سيتم حذف جميع البيانات الحالية من هذا الجهاز.");if(!ok)return;state=createInitialState();localStorage.removeItem(STORAGE_KEY);save();render()};el("printCert").onclick=()=>window.print();render()});
